import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { ProfileMenu, ThemeSwitcher } from "@/components/navbar";
import Link from "next/link";
import {
  Sheet,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Menu } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function Navbar({ isLoading }: { isLoading: boolean }) {
  // const auth = isLoading ? null : await getAuth();
  // const cookieStore = await cookies();
  return (
    <>
      <Sheet>
        <SheetTrigger asChild>
          <Button
            variant="outline"
            className="lg:hidden size-8 fixed top-4 right-4 z-10 bg-background border-border aspect-square"
          >
            <Menu className="size-4" />
          </Button>
        </SheetTrigger>

        <SheetContent>
          <SheetHeader>
            <SheetTitle>
              <Link href="/">
                <h2 className="font-bold">ITSME</h2>
              </Link>
            </SheetTitle>
          </SheetHeader>
          <div className="flex flex-col">
            <Button variant="ghost" className="w-full">
              <Link href="/projects" className="w-full text-start px-2">
                Projects
              </Link>
            </Button>
          </div>
          <SheetFooter>
            <div className="flex flex-row items-center gap-3">
              <ThemeSwitcher />
              <ProfileMenu user={null} />
            </div>
          </SheetFooter>
        </SheetContent>
      </Sheet>
      <div className="hidden lg:flex navbar-height bg-background border-b border-border flex-col items-center justify-center">
        <div className="w-full max-w-ui px-4 flex flex-row items-center justify-between">
          <div className="flex flex-row items-center gap-4">
            <Link href="/">
              <h2 className="font-bold">ITSME</h2>
            </Link>
            <div className="flex flex-row items-center gap-2.5">
              <Link href="/projects">
                <p className="text-sm">Projects</p>
              </Link>
            </div>
          </div>
          <div className="flex flex-row items-center gap-3">
            <ThemeSwitcher />
            <ProfileMenu user={null} />
          </div>
        </div>
      </div>
    </>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <Providers className={`${geistSans.className} antialiased`}>
        <div className="w-full h-full relative z-10 navbar-height">
          {/* Navbar */}
          {/* <Suspense fallback={<Navbar isLoading={true} />}>
            <Navbar isLoading={false} />
          </Suspense> */}
          {children}
        </div>
        <Toaster />
      </Providers>
    </html>
  );
}
